<div class="main-content">
				<div class="main-content-inner">
					<?php include _includes_.'inc.navigation.php'; ?>

					<div class="page-content">
					<?php include _includes_.'inc.template.php'; ?>
						<div class="page-header">
							<h1>
								Proyección Social
								<!-- <small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									3 styles with inline editable feature
								</small> -->
							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<div>
									<div id="user-profile-1" class="user-profile row">
										<div class="col-xs-12">
											<div class="media search-media">
												<div class="media-left">
													<a href="#">
														<img class="media-object" data-src="holder.js/72x72" />
													</a>
												</div>

												<div class="media-body">
													<div>
														<h4 class="media-heading">
															<a href="#" class="blue">Curso teórico deshidratación de Alimentos</a>
														</h4>
													</div>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, dignissimos rem facilis quaerat maiores. Et non asperiores adipisci sed ad, maxime quo deleniti nobis tempora. ...</p>

													<div class="search-actions text-center">

														<span class="blue bolder bigger-150">150</span>

														Inscritos
														<a class="search-btn-action btn btn-sm btn-block btn-info">INCRIBIRME</a>
													</div>
												</div>
											</div>
											<div class="media search-media">
												<div class="media-left">
													<a href="#">
														<img class="media-object" data-src="holder.js/72x72" />
													</a>
												</div>

												<div class="media-body">
													<div>
														<h4 class="media-heading">
															<a href="#" class="blue">Planeamiento Estratégico</a>
														</h4>
													</div>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, dignissimos rem facilis quaerat maiores. Et non asperiores adipisci sed ad, maxime quo deleniti nobis tempora. ...</p>

													<div class="search-actions text-center">

														<span class="blue bolder bigger-150">80</span>

														Inscritos
														<a class="search-btn-action btn btn-sm btn-block btn-info">INCRIBIRME</a>
													</div>
												</div>
											</div>
											<div class="media search-media">
												<div class="media-left">
													<a href="#">
														<img class="media-object" data-src="holder.js/72x72" />
													</a>
												</div>

												<div class="media-body">
													<div>
														<h4 class="media-heading">
															<a href="#" class="blue">Aplicación de buenas prácticas en laboratorio</a>
														</h4>
													</div>
													<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, dignissimos rem facilis quaerat maiores. Et non asperiores adipisci sed ad, maxime quo deleniti nobis tempora. ...</p>

													<div class="search-actions text-center">

														<span class="blue bolder bigger-150">68</span>

														Inscritos
														<a class="search-btn-action btn btn-sm btn-block btn-info">INCRIBIRME</a>
													</div>
												</div>
											</div>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>