<div class="main-content">
				<div class="main-content-inner">
					<?php include _includes_.'inc.navigation.php'; ?>

					<div class="page-content">
					<?php include _includes_.'inc.template.php'; ?>
						<div class="page-header">
							<h1>
								Redes Científicas
								<!-- <small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									3 styles with inline editable feature
								</small> -->
							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<div>
									<div id="user-profile-1" class="user-profile row">
										<div class="col-xs-12 col-sm-3 center">
											<div>
												<span class="profile-picture">
													<a href="http://alicia.concytec.gob.pe/vufind/" target="new">
														<img id="avatar" class="editable img-responsive" alt="Alex's Avatar" src="assets/images/redes/alicia.jpg" width="200" />
													</a>
												</span>

												<div class="space-4"></div>

												<div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
													<div class="inline position-relative">
														<a href="http://alicia.concytec.gob.pe/vufind/" target="new" class="user-title-label dropdown-toggle" data-toggle="dropdown">
															<i class="ace-icon fa fa-circle light-green"></i>
															&nbsp;
															<span class="white">Alicia.concytec.gob.pe</span>
														</a>
													</div>
												</div>
											</div>
											<div class="space-6"></div>
										</div>
										<div class="col-xs-12 col-sm-3 center">
											<div>
												<span class="profile-picture">
													<a href="http://www.sciencedirect.com/" target="new">
														<img id="avatar" class="editable img-responsive" alt="Alex's Avatar" src="assets/images/redes/science.jpg" width="200" />
													</a>
												</span>

												<div class="space-4"></div>

												<div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
													<div class="inline position-relative">
														<a href="http://www.sciencedirect.com/" target="new" class="user-title-label dropdown-toggle" data-toggle="dropdown">
															<i class="ace-icon fa fa-circle light-green"></i>
															&nbsp;
															<span class="white">sciencedirect.com</span>
														</a>
													</div>
												</div>
											</div>
											<div class="space-6"></div>
										</div>
										<div class="col-xs-12 col-sm-3 center">
											<div>
												<span class="profile-picture">
													<a href="http://www.redalyc.org/" target="new">
														<img id="avatar" class="editable img-responsive" alt="Alex's Avatar" src="assets/images/redes/redalyc.jpg" width="200" />
													</a>
												</span>

												<div class="space-4"></div>

												<div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
													<div class="inline position-relative">
														<a href="http://www.redalyc.org/" target="new" class="user-title-label dropdown-toggle" data-toggle="dropdown">
															<i class="ace-icon fa fa-circle light-green"></i>
															&nbsp;
															<span class="white">redalyc.org</span>
														</a>
													</div>
												</div>
											</div>
											<div class="space-6"></div>
										</div>
										<div class="col-xs-12 col-sm-3 center">
											<div>
												<span class="profile-picture">
													<a href="https://books.google.es/" target="new">
														<img id="avatar" class="editable img-responsive" alt="Alex's Avatar" src="assets/images/redes/google-books.jpg" width="200" />
													</a>
												</span>

												<div class="space-4"></div>

												<div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
													<div class="inline position-relative">
														<a href="https://books.google.es/" target="new" class="user-title-label dropdown-toggle" data-toggle="dropdown">
															<i class="ace-icon fa fa-circle light-green"></i>
															&nbsp;
															<span class="white">https://books.google.es</span>
														</a>
													</div>
												</div>
											</div>
											<div class="space-6"></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>